info:
  version: 1.0.0
  description: BSF initial local configuration

configuration:
  bsfName: BSF # the name of this BSF
  sbi: # service-based interface information
    scheme: http # the protocol for SBI (http or https)
    registerIPv4: <SBI_PREFIX>.21 # IP used to register to NRF
    bindingIPv4: <SBI_PREFIX>.21 # IP used to bind the service
    port: 8000 # port used to bind the service
    tls: # the local path of TLS key
      pem: config/TLS/bsf.pem # BSF TLS Certificate
      key: config/TLS/bsf.key # BSF TLS Private key
  nrfUri: http://<SBI_PREFIX>.10:8000 # a valid URI of NRF
  serviceNameList: # the SBI services provided by this BSF, refer to TS 29.522
    - nbsf-management # Nbsf_Management

# the kind of log output
  # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
  # ReportCaller: enable the caller report or not, value: true or false
logger:
  BSF:
    debugLevel: info
    ReportCaller: false
