info:
  version: 1.0.6
  description: SMF initial local configuration

configuration:
  smfName: SMF # the name of this SMF
  sbi: # Service-based interface information
    scheme: http # the protocol for sbi (http or https)
    registerIPv4: <SMF2_SBI_IP>  # IP used to register to NRF
    bindingIPv4: <SMF2_SBI_IP>  # IP used to bind the service
    port: 8000 # Port used to bind the service
    tls: # the local path of TLS key
      key: config/TLS/smf.key # SMF TLS Certificate
      pem: config/TLS/smf.pem # SMF TLS Private key
  serviceNameList: # the SBI services provided by this SMF, refer to TS 29.502
    - nsmf-pdusession # Nsmf_PDUSession service
    - nsmf-event-exposure # Nsmf_EventExposure service
    - nsmf-oam # OAM service
  snssaiInfos: # the S-NSSAI (Single Network Slice Selection Assistance Information) list supported by this AMF
    - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
        sst: <S_NSSAI_SST_2> # Slice/Service Type (uinteger, range: 0~255)
        sd: <S_NSSAI_SD_2> # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
      dnnInfos: # DNN information list
        - dnn: <DNN_1> # Data Network Name
          dns: # the IP address of DNS
            ipv4: 8.8.8.8
            ipv6: 2001:4860:4860::8888
    - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
        sst: <S_NSSAI_SST_2> # Slice/Service Type (uinteger, range: 0~255)
        sd: <S_NSSAI_SD_2> # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
      dnnInfos: # DNN information list
        - dnn: <DNN_2> # Data Network Name
          dns: # the IP address of DNS
            ipv4: 8.8.8.8
            ipv6: 2001:4860:4860::8888
  plmnList: # the list of PLMN IDs that this SMF belongs to (optional, remove this key when unnecessary)
    - mcc: <MCC> # Mobile Country Code (3 digits string, digit: 0~9)
      mnc: <MNC> # Mobile Network Code (2 or 3 digits string, digit: 0~9)
  locality: area1 # Name of the location where a set of AMF, SMF, PCF and UPFs are located
  pfcp: # the IP address of N4 interface on this SMF (PFCP)
    # addr config is deprecated in smf config v1.0.3, please use the following config
    nodeID: <SMF2_N4_IP> # the Node ID of this SMF
    listenAddr: <SMF2_N4_IP> # the IP/FQDN of N4 interface on this SMF (PFCP)
    externalAddr: <SMF2_N4_IP> # the IP/FQDN of N4 interface on this SMF (PFCP)
  userplaneInformation: # list of userplane information
    upNodes: # information of userplane node (AN or UPF)
      gNB1: # the name of the node
        type: AN # the type of the node (AN or UPF)
      upf3: # the name of the node (should be the same as UPF's sid)
        type: UPF # the type of the node (AN or UPF)
        nodeID: <UPF3_N4_IP> # the Node ID of this UPF
        addr: <UPF3_N4_IP> # the IP/FQDN of N4 interface on this UPF (PFCP)
        sNssaiUpfInfos: # S-NSSAI information list for this UPF
          - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
              sst: <S_NSSAI_SST_2> # Slice/Service Type (uinteger, range: 0~255)
              sd: <S_NSSAI_SD_2> # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
            dnnUpfInfoList: # DNN information list for this S-NSSAI
              - dnn: <DNN_1>
                pools:
                  - cidr: <IP_POOLS_3>
                staticPools:
                  - cidr: <STATIC_IP_POOLS_3>
        interfaces: # Interface list for this UPF (Now only support 1 interface for 1 type)
          - interfaceType: N3 # the type of the interface (N3 or N9)
            endpoints: # the IP address of this N3/N9 interface on this UPF
              - <UPF3_N3_IP>
            networkInstances: [<MEC_DNN_LIST><DNN_1>] # Data Network Name (DNN)
      upf4: # the name of the node (should be the same as UPF's sid)
        type: UPF # the type of the node (AN or UPF)
        nodeID: <UPF4_N4_IP> # the Node ID of this UPF
        addr: <UPF4_N4_IP> # the IP/FQDN of N4 interface on this UPF (PFCP)
        sNssaiUpfInfos: # S-NSSAI information list for this UPF
          - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
              sst: <S_NSSAI_SST_2> # Slice/Service Type (uinteger, range: 0~255)
              sd: <S_NSSAI_SD_2> # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
            dnnUpfInfoList: # DNN information list for this S-NSSAI
              - dnn: <DNN_2>
                pools:
                  - cidr: <IP_POOLS_4>
                staticPools:
                  - cidr: <STATIC_IP_POOLS_4>
        interfaces: # Interface list for this UPF (Now only support 1 interface for 1 type)
          - interfaceType: N3 # the type of the interface (N3 or N9)
            endpoints: # the IP address of this N3/N9 interface on this UPF
              - <UPF4_N3_IP>
            networkInstances: [<MEC_DNN_LIST><DNN_2>] # Data Network Name (DNN)
    links: # the topology graph of userplane, A and B represent the two nodes of each link
      - A: gNB1
        B: upf3
      - A: gNB1
        B: upf4
  # retransmission timer for pdu session modification command
  t3591:
    enable: true     # true or false
    expireTime: 16s   # default is 6 seconds
    maxRetryTimes: 3 # the max number of retransmission
  # retransmission timer for pdu session release command
  t3592:
    enable: true     # true or false
    expireTime: 16s   # default is 6 seconds
    maxRetryTimes: 3 # the max number of retransmission
  nrfUri: http://<SBI_PREFIX>.10:8000 # a valid URI of NRF
  urrPeriod: 10 # default usage report period in seconds
  urrThreshold: 1000 # default usage report threshold in bytes

# the kind of log output
# debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
# ReportCaller: enable the caller report or not, value: true or false
logger:
  SMF:
    debugLevel: info
    ReportCaller: false
  NAS:
    debugLevel: info
    ReportCaller: false
  NGAP:
    debugLevel: info
    ReportCaller: false
  Aper:
    debugLevel: info
    ReportCaller: false
  PFCP:
    debugLevel: info
    ReportCaller: false
