info:
  version: 1.0.7
  description: SMF initial local configuration

configuration:
  smfName: SMF # the name of this SMF
  sbi: # Service-based interface information
    scheme: http # the protocol for sbi (http or https)
    registerIPv4: <SBI_PREFIX>.7 # IP used to register to NRF
    bindingIPv4: <SBI_PREFIX>.7 # IP used to bind the service
    port: 8000 # Port used to bind the service
    tls: # the local path of TLS key
      key: cert/smf.key # SMF TLS Certificate
      pem: cert/smf.pem # SMF TLS Private key
  serviceNameList: # the SBI services provided by this SMF, refer to TS 29.502
    - nsmf-pdusession # Nsmf_PDUSession service
    - nsmf-event-exposure # Nsmf_EventExposure service
    - nsmf-oam # OAM service
  snssaiInfos: # the S-NSSAI (Single Network Slice Selection Assistance Information) list supported by this AMF
    - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
        sst: <S_NSSAI_SST_1> # Slice/Service Type (uinteger, range: 0~255)
        sd: <S_NSSAI_SD_1> # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
      dnnInfos: # DNN information list
        - dnn: <DNN_1> # Data Network Name
          dns: # the IP address of DNS
            ipv4: 8.8.8.8
            ipv6: 2001:4860:4860::8888
        - dnn: <DNN_3> # Data Network Name
          dns: # the IP address of DNS
            ipv4: 8.8.8.8
            ipv6: 2001:4860:4860::8888
        - dnn: <DNN_4> # Data Network Name
          dns: # the IP address of DNS
            ipv4: 8.8.8.8
            ipv6: 2001:4860:4860::8888
        - dnn: <DNN_5> # Data Network Name
          dns: # the IP address of DNS
            ipv4: 8.8.8.8
            ipv6: 2001:4860:4860::8888
        - dnn: <DNN_6> # Data Network Name
          dns: # the IP address of DNS
            ipv4: 8.8.8.8
            ipv6: 2001:4860:4860::8888
        - dnn: <DNN_7> # Data Network Name
          dns: # the IP address of DNS
            ipv4: 8.8.8.8
            ipv6: 2001:4860:4860::8888
        - dnn: <DNN_8> # Data Network Name
          dns: # the IP address of DNS
            ipv4: 8.8.8.8
            ipv6: 2001:4860:4860::8888
        - dnn: <DNN_9> # Data Network Name
          dns: # the IP address of DNS
            ipv4: 8.8.8.8
            ipv6: 2001:4860:4860::8888
        - dnn: <DNN_10> # Data Network Name
          dns: # the IP address of DNS
            ipv4: 8.8.8.8
            ipv6: 2001:4860:4860::8888
        - dnn: <DNN_11> # Data Network Name
          dns: # the IP address of DNS
            ipv4: 8.8.8.8
            ipv6: 2001:4860:4860::8888
        - dnn: <DNN_12> # Data Network Name
          dns: # the IP address of DNS
            ipv4: 8.8.8.8
            ipv6: 2001:4860:4860::8888
        - dnn: <DNN_13> # Data Network Name
          dns: # the IP address of DNS
            ipv4: 8.8.8.8
            ipv6: 2001:4860:4860::8888
        - dnn: <DNN_14> # Data Network Name
          dns: # the IP address of DNS
            ipv4: 8.8.8.8
            ipv6: 2001:4860:4860::8888
        - dnn: <DNN_15> # Data Network Name
          dns: # the IP address of DNS
            ipv4: 8.8.8.8
            ipv6: 2001:4860:4860::8888
        - dnn: <DNN_16> # Data Network Name
          dns: # the IP address of DNS
            ipv4: 8.8.8.8
            ipv6: 2001:4860:4860::8888
    - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
        sst: <S_NSSAI_SST_2> # Slice/Service Type (uinteger, range: 0~255)
        sd: <S_NSSAI_SD_2> # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
      dnnInfos: # DNN information list
        - dnn: <DNN_2> # Data Network Name
          dns: # the IP address of DNS
            ipv4: 8.8.8.8
            ipv6: 2001:4860:4860::8888

  plmnList: # the list of PLMN IDs that this SMF belongs to (optional, remove this key when unnecessary)
    - mcc: <MCC> # Mobile Country Code (3 digits string, digit: 0~9)
      mnc: <MNC> # Mobile Network Code (2 or 3 digits string, digit: 0~9)
  locality: area1 # Name of the location where a set of AMF, SMF, PCF and UPFs are located
  pfcp: # the IP address of N4 interface on this SMF (PFCP)
    # addr config is deprecated in smf config v1.0.3, please use the following config
    nodeID: <SMF_N4_IP> # the Node ID of this SMF
    listenAddr: <SMF_N4_IP> # the IP/FQDN of N4 interface on this SMF (PFCP)
    externalAddr: <SMF_N4_IP> # the IP/FQDN of N4 interface on this SMF (PFCP)
  userplaneInformation: # list of userplane information
    upNodes: # information of userplane node (AN or UPF)
      gNB1: # the name of the node
        type: AN # the type of the node (AN or UPF)
      UPF: # the name of the node (should be the same as UPF's sid)
        type: UPF # the type of the node (AN or UPF)
        nodeID: <UPF_N4_IP> # the Node ID of this UPF
        addr: <UPF_N4_IP> # the IP/FQDN of N4 interface on this UPF (PFCP)
        sNssaiUpfInfos: # S-NSSAI information list for this UPF
          - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
              sst: <S_NSSAI_SST_1> # Slice/Service Type (uinteger, range: 0~255)
              sd: <S_NSSAI_SD_1> # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
            dnnUpfInfoList: # DNN information list for this S-NSSAI
              - dnn: <DNN_1>
                pools:
                  - cidr: <IP_POOLS_1>
                staticPools:
                  - cidr: <STATIC_IP_POOLS_1>
          - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
              sst: <S_NSSAI_SST_2> # Slice/Service Type (uinteger, range: 0~255)
              sd: <S_NSSAI_SD_2> # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
            dnnUpfInfoList: # DNN information list for this S-NSSAI
              - dnn: <DNN_2>
                pools:
                  - cidr: <IP_POOLS_2>
                staticPools:
                  - cidr: <STATIC_IP_POOLS_2>

          - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
              sst: <S_NSSAI_SST_3> # Slice/Service Type (uinteger, range: 0~255)
              sd: <S_NSSAI_SD_3> # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
            dnnUpfInfoList: # DNN information list for this S-NSSAI
              - dnn: <DNN_3>
                pools:
                  - cidr: <IP_POOLS_3>
                staticPools:
                  - cidr: <STATIC_IP_POOLS_3>

          - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
              sst: <S_NSSAI_SST_4> # Slice/Service Type (uinteger, range: 0~255)
              sd: <S_NSSAI_SD_4> # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
            dnnUpfInfoList: # DNN information list for this S-NSSAI
              - dnn: <DNN_4>
                pools:
                  - cidr: <IP_POOLS_4>
                staticPools:
                  - cidr: <STATIC_IP_POOLS_4>
          - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
              sst: <S_NSSAI_SST_5> # Slice/Service Type (uinteger, range: 0~255)
              sd: <S_NSSAI_SD_5> # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
            dnnUpfInfoList: # DNN information list for this S-NSSAI
              - dnn: <DNN_5>
                pools:
                  - cidr: <IP_POOLS_5>
                staticPools:
                  - cidr: <STATIC_IP_POOLS_5>
          - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
              sst: <S_NSSAI_SST_6> # Slice/Service Type (uinteger, range: 0~255)
              sd: <S_NSSAI_SD_6> # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
            dnnUpfInfoList: # DNN information list for this S-NSSAI
              - dnn: <DNN_6>
                pools:
                  - cidr: <IP_POOLS_6>
                staticPools:
                  - cidr: <STATIC_IP_POOLS_6>
          - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
              sst: <S_NSSAI_SST_7> # Slice/Service Type (uinteger, range: 0~255)
              sd: <S_NSSAI_SD_7> # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
            dnnUpfInfoList: # DNN information list for this S-NSSAI
              - dnn: <DNN_7>
                pools:
                  - cidr: <IP_POOLS_7>
                staticPools:
                  - cidr: <STATIC_IP_POOLS_7>
          - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
              sst: <S_NSSAI_SST_8> # Slice/Service Type (uinteger, range: 0~255)
              sd: <S_NSSAI_SD_8> # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
            dnnUpfInfoList: # DNN information list for this S-NSSAI
              - dnn: <DNN_8>
                pools:
                  - cidr: <IP_POOLS_8>
                staticPools:
                  - cidr: <STATIC_IP_POOLS_8>
          - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
              sst: <S_NSSAI_SST_9> # Slice/Service Type (uinteger, range: 0~255)
              sd: <S_NSSAI_SD_9> # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
            dnnUpfInfoList: # DNN information list for this S-NSSAI
              - dnn: <DNN_9>
                pools:
                  - cidr: <IP_POOLS_9>
                staticPools:
                  - cidr: <STATIC_IP_POOLS_9>
          - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
              sst: <S_NSSAI_SST_10> # Slice/Service Type (uinteger, range: 0~255)
              sd: <S_NSSAI_SD_10> # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
            dnnUpfInfoList: # DNN information list for this S-NSSAI
              - dnn: <DNN_10>
                pools:
                  - cidr: <IP_POOLS_10>
                staticPools:
                  - cidr: <STATIC_IP_POOLS_10>
          - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
              sst: <S_NSSAI_SST_11> # Slice/Service Type (uinteger, range: 0~255)
              sd: <S_NSSAI_SD_11> # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
            dnnUpfInfoList: # DNN information list for this S-NSSAI
              - dnn: <DNN_11>
                pools:
                  - cidr: <IP_POOLS_11>
                staticPools:
                  - cidr: <STATIC_IP_POOLS_11>
          - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
              sst: <S_NSSAI_SST_12> # Slice/Service Type (uinteger, range: 0~255)
              sd: <S_NSSAI_SD_12> # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
            dnnUpfInfoList: # DNN information list for this S-NSSAI
              - dnn: <DNN_12>
                pools:
                  - cidr: <IP_POOLS_12>
                staticPools:
                  - cidr: <STATIC_IP_POOLS_12>
          - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
              sst: <S_NSSAI_SST_13> # Slice/Service Type (uinteger, range: 0~255)
              sd: <S_NSSAI_SD_13> # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
            dnnUpfInfoList: # DNN information list for this S-NSSAI
              - dnn: <DNN_13>
                pools:
                  - cidr: <IP_POOLS_13>
                staticPools:
                  - cidr: <STATIC_IP_POOLS_13>
          - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
              sst: <S_NSSAI_SST_14> # Slice/Service Type (uinteger, range: 0~255)
              sd: <S_NSSAI_SD_14> # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
            dnnUpfInfoList: # DNN information list for this S-NSSAI
              - dnn: <DNN_14>
                pools:
                  - cidr: <IP_POOLS_14>
                staticPools:
                  - cidr: <STATIC_IP_POOLS_14>
          - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
              sst: <S_NSSAI_SST_15> # Slice/Service Type (uinteger, range: 0~255)
              sd: <S_NSSAI_SD_15> # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
            dnnUpfInfoList: # DNN information list for this S-NSSAI
              - dnn: <DNN_15>
                pools:
                  - cidr: <IP_POOLS_15>
                staticPools:
                  - cidr: <STATIC_IP_POOLS_15>
          - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
              sst: <S_NSSAI_SST_16> # Slice/Service Type (uinteger, range: 0~255)
              sd: <S_NSSAI_SD_16> # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
            dnnUpfInfoList: # DNN information list for this S-NSSAI
              - dnn: <DNN_16>
                pools:
                  - cidr: <IP_POOLS_16>
                staticPools:
                  - cidr: <STATIC_IP_POOLS_16>

        interfaces: # Interface list for this UPF
          - interfaceType: N3 # the type of the interface (N3 or N9)
            endpoints: # the IP address of this N3/N9 interface on this UPF
              - <UPF_N3_IP>
            networkInstances: [<DNN_LIST>] # Data Network Name (DNN)
    links: # the topology graph of userplane, A and B represent the two nodes of each link
      - A: gNB1
        B: UPF
  # retransmission timer for pdu session modification command
  t3591:
    enable: true     # true or false
    expireTime: 16s   # default is 6 seconds
    maxRetryTimes: 3 # the max number of retransmission
  # retransmission timer for pdu session release command
  t3592:
    enable: true     # true or false
    expireTime: 16s   # default is 6 seconds
    maxRetryTimes: 3 # the max number of retransmission
  nrfUri: http://<SBI_PREFIX>.10:8000 # a valid URI of NRF
  #urrPeriod: 10 # default usage report period in seconds
  #urrThreshold: 1000 # default usage report threshold in bytes

logger: # log output setting
  enable: true # true or false
  level: info # how detailed to output, value: trace, debug, info, warn, error, fatal, panic
  reportCaller: false # enable the caller report or not, value: true or false
