info:
  version: 1.0.0
  description: AMF initial local configuration

configuration:
  amfName: AMF # the name of this AMF
  ngapIpList:  # the IP that AMF listening on N2 interface (connent to RAN)
    - 127.0.0.1
  sbi:
    scheme: http # http or https
    registerIPv4: 127.0.0.1 # IP used to register to NRF
    bindingIPv4: 127.0.0.1  # IP used to bind the service
    port: 29518
  serviceNameList: # the services provided by this AMF
    - namf-comm # Namf_Communication service
    - namf-evts # Namf_EventExposure service
    - namf-mt   # Namf_MT service
    - namf-loc  # Namf_Location service
    - namf-oam  # OAM service
  servedGuamiList: # Guami(the Globally Unique AMF ID), an AMF can be configured with one or more GUAMIs.
    - plmnId:
        mcc: 208
        mnc: 93
      amfId: cafe00
  supportTaiList:  # TAI(Tracking Area Identifier), the TAI list which is supported by this AMF
    - plmnId:
        mcc: 208
        mnc: 93
      tac: 1
  plmnSupportList: # PLMN(Public land mobile network), the PLMNs which is supported by this AMF
    - plmnId:
        mcc: 208
        mnc: 93
      snssaiList:
        - sst: 1
          sd: 010203
        - sst: 1
          sd: 112233
  supportDnnList:  # DNN(Data Network Name), the DNN list which is supported by this AMF
    - internet
  nrfUri: http://localhost:29510 # a valid URI of NRF
  security:  # NAS security parameters
    integrityOrder: # the algorithm for integrity check
      - NIA2
      # - NIA0
    cipheringOrder: # the algorithm for ciphering check
      - NEA0
      # - NEA2
  networkName:  # the name of this core network
    full: free5GC
    short: free
  t3502Value: 720  # timer value at UE side, unit is seconds
  t3512Value: 3600 # timer value at UE side, unit is seconds
  non3gppDeregistrationTimerValue: 3240 # timer value at UE side, unit is seconds
  # retransmission timer for paging message
  t3513:
    enable: true     # true or false
    expireTime: 6s   # default is 6 seconds
    maxRetryTimes: 4 # the max number of retransmission
  # retransmission timer for NAS Deregistration Request message
  t3522:
    enable: true     # true or false
    expireTime: 6s   # default is 6 seconds
    maxRetryTimes: 4 # the max number of retransmission
  # retransmission timer for NAS Registration Accept message
  t3550:
    enable: true     # true or false
    expireTime: 6s   # default is 6 seconds
    maxRetryTimes: 4 # the max number of retransmission
  # retransmission timer for NAS Authentication Request/Security Mode Command message
  t3560:
    enable: true     # true or false
    expireTime: 6s   # default is 6 seconds
    maxRetryTimes: 4 # the max number of retransmission
  # retransmission timer for NAS Notification message
  t3565:
    enable: true     # true or false
    expireTime: 6s   # default is 6 seconds
    maxRetryTimes: 4 # the max number of retransmission

# the kind of log output
  # debugLevel: how detialed to output, value: trace, debug, fatal, panic, error, warn, info
  # ReportCaller: enable the caller report or not, value: true or false
logger:
  AMF:
    debugLevel: info
    ReportCaller: false
  NAS:
    debugLevel: info
    ReportCaller: false
  FSM:
    debugLevel: info
    ReportCaller: false
  NGAP:
    debugLevel: info
    ReportCaller: false
  Aper:
    debugLevel: info
    ReportCaller: false
  PathUtil:
    debugLevel: info
    ReportCaller: false
  OpenApi:
    debugLevel: info
    ReportCaller: false