info:
  version: 1.0.0
  description: AUSF initial local configuration

configuration:
  sbi:
    scheme: http
    registerIPv4: 127.0.0.9 # IP used to register to NRF
    bindingIPv4: 127.0.0.9  # IP used to bind the service
    port: 8000
  serviceNameList:
    - nausf-auth
  nrfUri: http://127.0.0.10:8000
  plmnSupportList:
    - mcc: 208
      mnc: 93
    - mcc: 123
      mnc: 45
  groupId: ausfGroup001

logger:
  AUSF:
    debugLevel: info
    ReportCaller: false
  PathUtil:
    debugLevel: info
    ReportCaller: false
  OpenApi:
    debugLevel: info
    ReportCaller: false
