info:
  version: 1.0.0
  description: AUSF initial local configuration

configuration:
  sbi:
    scheme: http # the protocol for sbi (http or https)
    registerIPv4: 127.0.0.9 # IP used to register to NRF
    bindingIPv4: 127.0.0.9  # IP used to bind the service
    port: 8000 # Port used to bind the service
  serviceNameList: # the SBI services provided by this AMF, refer to TS 29.510
    - nausf-auth # Nausf_UEAuthentication service
  nrfUri: http://127.0.0.10:8000 # a valid URI of NRF
  plmnSupportList: # PLMN(Public land mobile network), the PLMNs supported by this AUSF
    - mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
      mnc: 93  # Mobile Network Code (2 or 3 digits string, digit: 0~9)
    - mcc: 123
      mnc: 45
  groupId: ausfGroup001 # id for the group of the AUSF

# the kind of log output
  # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
  # ReportCaller: enable the caller report or not, value: true or false
logger:
  AUSF:
    debugLevel: info
    ReportCaller: false
  PathUtil:
    debugLevel: info
    ReportCaller: false
  OpenApi:
    debugLevel: info
    ReportCaller: false
