info:
  version: 1.0.2
  description: N3IWF initial local configuration

configuration:
  N3IWFInformation:
    GlobalN3IWFID: # ID used to globally identify an N3IWF
      PLMNID: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
        MCC: # Mobile Country Code (3 digits string, digit: 0~9)
          208
        MNC: # Mobile Network Code (2 or 3 digits string, digit: 0~9)
          93
      N3IWFID: # ID used to identify an N3IWF in PLMN (uinteger, range: 0~65535)
        135
    Name: # The name of this N3IWF
      free5GC_N3IWF
    SupportedTAList: # Tracking Area supported by this N3IWF
      - TAC: # Tracking Area Code (3 bytes hex string, range: 000000~FFFFFF)
          000001
        BroadcastPLMNList: # Refer to TS 38.413
          - PLMNID: # Public Land Mobile Network ID
              MCC: # Mobile Country Code (3 digits string, digit: 0~9)
                208
              MNC: # Mobile Network Code (2 or 3 digits string, digit: 0~9)
                93
            TAISliceSupportList: # Network Slice supported in this TAI
              - SNSSAI: # Single Network Slice Selection Assistance Information
                  SST: # Slice/Service Type (1 byte hex string, range: 0~F)
                    1
                  SD: # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
                    010203
              - SNSSAI:
                  SST:
                    1
                  SD:
                    112233

  # --- N2 Interfaces ---
  AMFSCTPAddresses: # the IP list of N2 interfaces (SCTP) on AMF when using NGAP
    - IP:
      - 127.0.0.18
  NASTCPPort: # TCP port which the NAS listens on
    20000

  # --- Nwu Interfaces ---
  IKEBindInterfaceName: # Nwu interface name (IKE) on this N3IWF
    ens39
  IKEBindAddress: # Nwu interface  IP address (IKE) on this N3IWF
    172.16.2.100
  IPSecTunnelAddress: # Tunnel IP address of XFRM interface on this N3IWF
    10.0.0.1
  UEIPAddressRange: # IP address pool allocated to UE in IPSec tunnel
    10.0.0.0/24
  XFRMInterfaceName: # Prefix of XFRM interface name created by N3IWF
    xfrmi
  XFRMInterfaceID: # XFRM interface if_id for IPSec routing (Any value except to 0, default value is 7 if not defined)
    1

  # --- N3 Interfaces ---
  GTPBindAddress: # IP address of N3 interface (GTP) on this N3IWF
    127.0.0.33

  FQDN: # FQDN of this N3IWF
    n3iwf.free5gc.org

  # --- Security ---
  PrivateKey: # Private key file path
    config/TLS/n3iwf.key

  CertificateAuthority: # Certificate Authority (CA) file path
    config/TLS/n3iwf.pem

  Certificate: # Certificate file path
    config/TLS/n3iwf.pem

# the kind of log output
  # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
  # ReportCaller: enable the caller report or not, value: true or false
logger:
  N3IWF: # The default log level is DEBUG to print SA keys. Please change it to INFO when deployed.
    debugLevel: trace
    ReportCaller: false
  NGAP:
    debugLevel: info
    ReportCaller: false
  Aper:
    debugLevel: info
    ReportCaller: false
