info:
  version: 1.0.0
  description: NRF initial local configuration

configuration:
  MongoDBName: free5gc
  MongoDBUrl: mongodb://127.0.0.1:27017
  sbi:
    scheme: http
    registerIPv4: 127.0.0.10 # IP used to serve NFs or register to another NRF
    bindingIPv4: 127.0.0.10  # IP used to bind the service
    port: 8000
  DefaultPlmnId:
    mcc: 208
    mnc: 93
  serviceNameList:
    - nnrf-nfm
    - nnrf-disc

logger:
  NRF:
    debugLevel: info
    ReportCaller: false
  PathUtil:
    debugLevel: info
    ReportCaller: false
  OpenApi:
    debugLevel: info
    ReportCaller: false
  MongoDBLibrary:
    debugLevel: info
    ReportCaller: false
