info:
  version: 1.0.0
  description: UDR initial local configuration

configuration:
  sbi:
    scheme: http
    registerIPv4: 127.0.0.4 # IP used to register to NRF
    bindingIPv4: 127.0.0.4  # IP used to bind the service
    port: 8000
  mongodb:
    name: free5gc
    url: mongodb://localhost:27017
  nrfUri: http://127.0.0.10:8000

logger:
  UDR:
    debugLevel: info
    ReportCaller: false
  MongoDBLibrary:
    debugLevel: info
    ReportCaller: false
  PathUtil:
    debugLevel: info
    ReportCaller: false
  OpenApi:
    debugLevel: info
    ReportCaller: false
