info:
  version: 1.0.1
  description: PCF initial local configuration

configuration:
  pcfName: PCF # the name of this PCF
  sid: pcf1 # CMI service ID
  sbi: # Service-based interface information
    scheme: http # the protocol for sbi (http or https)
    registerIPv4: 10.100.200.8 # IP used to register to NRF
    bindingIPv4: 10.100.200.8 # IP used to bind the service
    port: 8000 # port used to bind the service
  timeFormat: 2019-01-02 15:04:05 # time format of this PCF
  defaultBdtRefId: BdtPolicyId- # BDT Reference ID, indicating transfer policies of background data transfer.
  nrfUri: http://10.100.200.6:8000  # a valid URI of NRF
  serviceList:   # the SBI services provided by this PCF, refer to TS 29.507
    - serviceName: npcf-am-policy-control
    - serviceName: npcf-bdtpolicycontrol
    - serviceName: npcf-eventexposure
    - serviceName: npcf-policyauthorization
      suppFeat: 3
    - serviceName: npcf-smpolicycontrol
      suppFeat: 3fff
    - serviceName: npcf-ue-policy-control
  mongodb:       # the mongodb connected by this PCF
    name: free5gc # name of the mongodb
    url: mongodb://db:27017 # a valid URL of the mongodb

# the kind of log output
  # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
  # ReportCaller: enable the caller report or not, value: true or false
logger:
  PCF:
    debugLevel: info
    ReportCaller: false
